ASSUME CS:CODE, DS:DATA
DATA SEGMENT
MSG1   DB 0DH,0AH,"ENTER THE NUMBER OF ROWS: $"
MSG2   DB 0DH,0AH,"ENTER THE NUMBER OF COLUMNS: $"
SPACE  DB " $"
MSG3   DB 0DH,0AH,"ENTER THE FIRST MATRIX A: $"
MSG4   DB 0DH,0AH,"ENTER THE SECOND MATRIX B: $"
MSG5   DB 0DH,0AH,"SUM OF TWO MATRIX IS: $"
NL     DB 0DH,0AH,"$"
ROWS   DB 00H
COLS   DB 00H
MATA   DB 25 DUP('$')
MATB   DB 25 DUP('$')
MATSUM DW 25 DUP('$')
ELE    DB ?
DATA ENDS

READ MACRO NUM
MOV AH, 01H
INT 21H
SUB AL,30H
MOV NUM, AL
ENDM

PRINT MACRO S
MOV AH, 09H
MOV DX, OFFSET S
INT 21H
ENDM

PRINTMATRIX MACRO MATRIX
			MOV   SI, OFFSET MATRIX
			MOV   CX, 00H
PRINTROWS:  CMP   CL, ROWS
			JZ    EXITPRINT
			MOV   BX, 00H

PRINTCOLS:  CMP   BL, COLS
			JZ    EXITCOLS
			MOV   DL,[SI]
			MOV   AH,00H
			MOV   AL,DL
			CMP   AL,0AH
			JL    NLOP
			AAA
NLOP:	MOV   ELE,AL
		MOV   DL,AH
		ADD   DL,30H
		MOV   AH,02H
		INT   21H
		MOV   DL,ELE
		ADD   DL,30H
		MOV   AH,02H
		INT   21H

		PRINT SPACE
		INC   SI
		INC   BX
		JMP   PRINTCOLS
EXITCOLS:	PRINT NL
			INC   CX
			JMP   PRINTROWS
EXITPRINT:  
ENDM

CODE SEGMENT
START:	MOV         AX, DATA
		MOV         DS, AX
		MOV         ES, AX
		PRINT       MSG1
		READ        ROWS             	;READ ROWS
		PRINT       NL
		PRINT       MSG2
		READ        COLS             	;READ COLS
		PRINT       NL
		PRINT       MSG3
		MOV         SI, OFFSET MATA  	;READ MATRIX A
		CALL        READMATRIX
		PRINT       NL
		PRINT       MSG4
		MOV         SI, OFFSET MATB  	;READ MATRIX B
		CALL        READMATRIX
		PRINT       NL
		MOV         AL, ROWS
		MOV         CL, COLS
		MUL         CL
		MOV         BX, 00H
		MOV         CX,AX
ADDMATRIX:	CMP         BX, CX
			JGE         EXITADD
			MOV         SI, OFFSET MATA
			MOV         DL, [BX][SI]
			MOV         DI, OFFSET MATB
			MOV         DH, [BX][DI]
			ADD         DL, DH
			MOV         AL,DL
			MOV         SI, OFFSET MATSUM
			MOV         [BX][SI], AX
			INC         BX
			JMP         ADDMATRIX
EXITADD:	PRINT       MSG5
			PRINT       NL
			PRINTMATRIX MATSUM

FINISH:	MOV         AH, 4CH
		INT         21H

READMATRIX 	PROC NEAR
			MOV         CL, ROWS
			MOV         AL, COLS
			MUL         CL
			MOV         CX, AX
			MOV         BL,0H
			PRINT       NL
READARRAY:	READ        ELE
			PRINT       SPACE
			MOV         AL, ELE
			MOV         [SI], AL
			INC         SI
			INC         BL
			CMP         BL ,COLS
			JNZ         LOP
			PRINT       NL
			MOV         BL,0H
LOP:	LOOP        READARRAY
		RET
READMATRIX ENDP

CODE ENDS
END START